language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
    - "git fetch origin master:pylint-basis"
    - "git diff pylint-basis --name-only  -- '*.py' > CHANGED_PY_FILES"
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git#egg=xblock-sdk"
    - "pip install -r requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/test-requirements.txt"
    - "pip install --ignore-installed -r test_requirements.txt"
    - "pip uninstall -y xblock-mentoring && python setup.py sdist && pip install dist/xblock-mentoring-0.1.tar.gz"
script:
    - pep8 mentoring --max-line-length=120
    # Run pylint on any modified .py files but since there are a lot of issues right now, don't make it fail the build:
    - "[ -s CHANGED_PY_FILES ] && (cat CHANGED_PY_FILES | xargs pylint || echo -e \\\\nWARNING: PYLINT ERRORS) || echo pylint skipped"
    - python tests/manage.py test --rednose
notifications:
  email: false
addons:
  firefox: "36.0"
